diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=BJY029
user.email=go333dragon@gmail.com
difftool.sourcetree.cmd='' 
mergetool.sourcetree.cmd='' 
mergetool.sourcetree.trustexitcode=true
credential.helperselector.selected=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.autocrlf=input
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.autocrlf=true
lfs.repositoryformatversion=0
remote.origin.url=https://github.com/BJY029/Unity-Project-for-pandora-cube.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
lfs.https://github.com/BJY029/Unity-Project-for-pandora-cube.git/info/lfs.access=basic
branch.main.remote=origin
branch.main.merge=refs/heads/main
